services:
  - type: web
    name: shelfpulse-api
    runtime: python
    region: oregon  # or any region close to your users
    plan: free      # or "starter" if free tier limits are too low
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /
